{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}-env
  labels:
    app: {{ .Release.Name }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStore }}
    kind: SecretStore
  target:
    name: {{ .Release.Name }}-env
    creationPolicy: Owner
  data:
    {{- range $name, $secret := .Values.externalSecret.env }}
    - secretKey: {{ $name | quote }}
      remoteRef:
        key: {{ $secret | quote }}
    {{- end }}
{{- end }}
