{{- if and .Values.storage (eq .Values.storage.type "pvc") }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data
  labels:
    app: {{ .Release.Name }}
spec:
  accessModes:
    {{- toYaml .Values.storage.pvc.accessModes | nindent 4 }}
  {{- if .Values.storage.pvc.storageClassName }}
  storageClassName: {{ .Values.storage.pvc.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.pvc.size }}
{{- end }}
