apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Release.Name }}
  annotations:
    # This annotation is required for Workload Identity
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.workloadIdentity.gcpServiceAccount | quote }}
